
    Description (
	"The CP2550.\n+
	"CP (Caminhos-de-Ferro Portugueses) acquired 20 locomotives of this series and enterede service in 1956.\n+
	"They started operating in the North Line as soon as it was completly electrified, taking the fast passenger trains between Lisbon and Oporto.\n+
	"In the 90's they left passenger services and were entirely dedicated to cargo trains.\n\n"+
	"Locomotive builder: Alsthom-Henchel-Siemens (Groupment 50Hz).\n\n"+
	"Power source: Catenary from stationary electric generator.\n\n"+
	"Continuous power rating: 4x529kW = 2116kW\n\n"+
	"Traction : 4 Alsthom TAO 645 A1 engines\n\n"+
	"Max. speed: 120 km/h - 75mph"
    )
    