
	DoesBrakeCutPower( 1 )
	DoesHornTriggerBell( 0 )
	RunUpTimeToMaxForce ( 30 )
	BrakeCutsPowerAtBrakeCylinderPressure ( 15 )
	MaxSandingTime( 1200 )

	MaxDieselLevel ( 757l )
	DieselUsedPerHourAtMaxPower ( 94.64gal )
	DieselUsedPerHourAtIdle ( 7.57l )

	DieselSmokeEffectInitialMagnitude( 0.8 )
	DieselSmokeEffectMaxMagnitude( 1.4 )
	DieselSmokeEffectInitialSmokeRate( 0.2 )
	DieselSmokeEffectMaxSmokeRate( 1.9 )

	DieselEngineIdleRPM( 350 )
	DieselEngineMaxRPM( 1800 )
	DieselEngineSpeedOfMaxTractiveEffort( 7mph )
     	DieselEngineMaxRPMChangeRate( 65 )

	EngineBrakesControllerDirectControlExponent( 1 )

	ORTS ( ORTSWheelSlipCausesThrottleDown ( 1 ) )
	ORTS ( ORTSEmergencyCausesPowerDown    ( 0 ) )
	ORTS ( ORTSEmergencyCausesThrottleDown ( 1 ) )
