
    Description (
	"Sentinel 1150 diesel switcher; First unit was built in 1966.\n\n"+
 	"Locomotive type: Diesel with hydraulic transmission\n\n"+
 	"Power source: Diesel, Rolls Royce C8 TFL MK IV 8 Cyl\n\n"+
 	"Power: 348hp\n\n"+
 	"Max. speed: 40 mph\n\n"+
 	"Wheel configuration: Six 43in linked by rods\n\n"+
 	"Height: 11 ft. (3.365 m)\n\n"+
 	"Weight: 41.3 U.S. tons (42 metric tons)\n\n"+
 	"Length: 28 ft. (8.517 m)\n\n"+
 	"Width: 9.5 ft. (2.9 m)"
    )
    