
Comment ( Standard ORTS Diesel Engine for CP 1500 Alco )
Comment ( Performance Ratings == Gross HP 2185 == Traction HP 1730 == CTE 21000kg @ 21kph==81%eff. == STE 17000kg )
Comment ( Performance Ratings == Gross HP 2185 == Traction HP 1730 == CTE 46297lb @ 13mph==81%eff. == STE 37479lb )
Comment ( Mass 244713lbs = 111t == metric, Adhesion Factor = 22% )

Comment ( *** Diesel Engine *** )
	Type					( Diesel )
	MaxPower				( 1176.798kW ) #(* 1600cv estimados*)
	MaxVelocity				( 120kmh )
	MaxDieselLevel			( 2976l )
	DieselEngineSpeedOfMaxTractiveEffort ( 21kmh )
	DieselEngineType 			( electric )


Comment ( *** General *** )
	WheelRadius			( 0.508m ) #(* comprovado em ficha técnica nº8 ed1987*)
	Sanding			( 25mph )
	ORTSNumberDriveAxles 	( 4 )
	DoesHornTriggerBell	( 0 )
	ORTSDriveWheelWeight	( 76t ) #(* comprovado em ficha técnica nº8 ed1987*)

Comment ( *** Electric Motor *** )
	MaxCurrent 			( 1500A )
	ORTSElectricTrainSupply ( Mode ( Unfitted ))