
    Description (
	"The CP2620 is a Portuguese variant of the SNCF (France) class BB 7200.\n"+
	"CP (Caminhos-de-Ferro Portugueses) acquired 12 of these units in 1974 and later acquired an aditional 9 (the 2620 subseries).\n"+
	"They made their service in all passenger trains as well as cargo trains on the Lisbon-Porto Route.\n"+
	"In 1993, they have been assigned only to Intercities and Alfa services but even the Alfa service was taken from them in 1998 with the arrival of the 4000 Pendolino.\n\n"+
	"Era 1\n"+
	"EP Brakes\n"+
	"Great Speed(GV) gear ratio\n"+
	"Locomotive builder: Alsthom France.\n"+
	"Power source: Catenary from stationary electric generator.\n"+
	"Continuous power rating: 2x1470kW = 2940kW\n"+
	"Traction : 2 Alsthom TAB 660 D1 motors\n"+
	"Max. speed GV: 160 km/h - great speed"
    )
    