
    EngineOperatingProcedures (
    "To move forward\n"+
    "1. Press the P key to raise the pantograph\n"+
    "2. Press the O key to close the main circuit breaker. It will close when you hear it.\n"+
    "3.	Press the W key to move the Reverser to Forward.\n"+
    "4.	Press the ; (SEMICOLON) key to release the train brakes.\n"+
    "5.	Press the D key to increase the throttle setting.\n"+
    "6.	Do not go above 1400A at beginning of movement.\n"+
    "	Do not go above 1200A for tap system step-by-step use or 1100A in auto tap.\n"+
    "   Never go beyond 1050A in full power with 5 shunts (5 last position of throttle).\n\n"+
    "To slow the train\n"+
    "1.	Press the A key to move the throttle to a lower setting.\n"+
    "2.	Use the brakes to further reduce speed if desired.\n\n"+   
    "To apply the train brakes\n"+
    "1.	Press the ' (APOSTROPHE) key to apply the train brakes.\n"+
    "2. Use 0.5bar for slowing down and use 1.0bar for stoping the train"\n\n"+
    "To release the train brakes\n"+
    "1. Press the ; (SEMICOLON) key to release the train brakes.\n\n"+
    "To activate emergency braking\n"+
    "1.	Press the A key to reduce the throttle to Idle.\n"+
    "2.	Press the BACKSPACE key to activate emergency braking.\n\n"+
    "To back up\n"+
    "1.	Bring your train to a full stop.\n"+
    "2.	Press the S key to move the Reverser to the Reverse position.\n"+
    "3.	Press the ; (SEMICOLON)  to release the brakes.\n"+
    "4.	Slowly advance the throttle lever (D key)."
    )
      