
    	Description (	
	"CP 1800 Series diesel-electric locomotive\n"+
	"Partes Mecanicas: English Electric\n"+
	"Motor Diesel: English Electric\n"+
	"Transmissao: English Electric\n"+
	"Freio: Westinghouse Brake and Signalt\n"+
	"Tipo da Locomotiva: LD 937 C\n"+
	"Potencia Nominal da Locomotiva (rodas): 2020 Cv\n"+
	"Disposicso dos Rodados: CO CO\n"+
	"Diametro das rodas (novas): 1100 mm\n"+
	"Numero de Cabinas de Conducao: 2\n"+
	"Freio Pneumatico: Ar-Vacuo «Dual»\n"+
	"Freio Dinamico: Nao tem\n"+
	"Areeiros (Número): 8\n"+
	"Sistema de Homem Morto: Davies & Metcalfe/Oerlinkon\n"+
	"Comando em Unidades Multiplas: ate 2 - Aclopav. as 1400\n"+
	"Lubrificadores de Verdugos: Lubrovia\n"+
	"Registador de Velocidade: Hasler"
    	)
    	