
    	Description (	
	"CP 1800 Series diesel-electric locomotive\n"+
	"Partes Mecânicas: English Electric\n"+
	"Motor Diesel: English Electric\n"+
	"Transmissão: English Electric\n"+
	"Freio: Westinghouse Brake and Signalt\n"+
	"Tipo da Locomotiva: LD 937 C\n"+
	"Potência Nominal da Locomotiva (rodas): 2020 Cv\n"+
	"Disposição dos Rodados: CO CO\n"+
	"Diâmetro das rodas (novas): 1100 mm\n"+
	"Número de Cabinas de Condução: 2\n"+
	"Freio Pneumático: Ar-Vácuo «Dual»\n"+
	"Freio Dinâmico: Não tem\n"+
	"Areeiros (Número): 8\n"+
	"Sistema de Homem Morto: Davies & Metcalfe/Oerlinkon\n"+
	"Comando em Unidades Multiplas: até 2 - Aclopav. às 1400\n"+
	"Lubrificadores de Verdugos: Lubrovia\n"+
	"Registador de Velocidade: Hasler"
    	)
    	