
	Effects (
		DieselSpecialEffects (
			Exhaust1 (
				-0.224 4.478 -3.11
				0.5 0.5 0
				0.2
			)
			Exhaust2 (
				0.662 4.478 2.417
				-0.5 0.5 0
				0.2
			)
		)
	)
comment ( Parece ter uma boa cor para as 1320 mas precisa de mais fumo inicial
	DieselSmokeEffectInitialMagnitude ( 0.7 )
	DieselSmokeEffectMaxMagnitude     ( 1.5 )
	DieselSmokeEffectInitialSmokeRate ( 0.7 )
	DieselSmokeEffectMaxSmokeRate     ( 1.5 )
)