
    	Sound (	"..\\sound\\pt_sound\\genptwag1.sms" )
	Lights ( 1
		Light (
		Comment( Luz Rectaguarda )
		Type ( 0 )
		Conditions (
				Service( 2 )
				Unit ( 3 )
				)
		Cycle ( 0 )
		FadeIn ( 0.5 )
		FadeOut ( 0.5 )
		States ( 1
			State (
				Duration ( 0 )
					LightColour ( 80ff0000 )
				Position ( -0.46 1.5 -4.455 )
				Azimuth ( -180 -180 -180 )
				Transition ( 0 )
				Radius ( 1 )
				)
			)
		)
	)
