
Comment ( *************** Brakes - Wagon Section - General ********************** )
	BrakeEquipmentType( "Handbrake, Vacuum_brake, Auxilary_reservoir" )
	BrakeSystemType( "Vacuum_single_pipe" )
	MaxBrakeForce					( 40kN )
	MaxHandbrakeForce 				( 12kN )


	BrakePipeVolume 				( 0.62ft^3 )
	BrakeCylinderPressureForMaxBrakeBrakeForce 	( 21.0inHg ) Comment (* not yet functional *)
	ORTSNumberBrakeCylinders 			( 2 )
	ORTSBrakeCylinderSize 				( 21in )
	ORTSAuxilaryResCapacity 			( 2.25ft^3 )
	MaxReleaseRate 					( 50.0 )
	MaxApplicationRate 				( 10.0 )
	ORTSDirectAdmissionValve 			( 0 )
	ORTSBrakeShoeFriction ( 0.0 0.49 8.0 0.436 16.1 0.4 24.1 0.371 32.2 0.35 40.2 0.336 48.3 0.325 56.3 0.318 64.4 0.309 72.2 0.304 80.5 0.298 88.5 0.295 96.6 0.289 104.6 0.288 )
