
    	Sound (	"..\\sound\\pt_sound\\genptwag1.sms" )
	Lights ( 1
		Light (
			Comment( Luz Rectaguarda )
			Type ( 0 )
			Conditions (
				Service ( 2 )
				Unit ( 3 )
			)
			Cycle ( 0 )
			FadeIn ( 0.15 )
			FadeOut ( 0.15 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( ffff0000 )
					Position ( -0.8 2 -3.91 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.50 )
				)
			)
		)
	)
	