
Comment ( *************** Brakes - Wagon Section - General ********************** )
	BrakeEquipmentType ( "Triple_Valve,Distributor,auxilary_reservoir,ep_brake,emergency_brake_reservoir,Handbrake" )
	BrakeSystemType								( "Air_Twin_Pipe" )
	MaxBrakeForce								( 163.28kN )
	MaxHandbrakeForce 							( 59.918kN )

	TripleValveRatio							( 2.8 )
	MaxReleaseRate								( 1.04bar/s )
	MaxApplicationRate							( 1.04bar/s )
	MaxAuxilaryChargingRate							( 1.04bar/s )
	BrakeCylinderPressureForMaxBrakeBrakeForce 				( 5.0bar )
	BrakePipeVolume 							( 0.41ft^3 )

	BrakeDistributorTrainPipeAuxResPressureDifferenceForApplication 	( 1 )
	BrakeDistributorEmergencyApplicationPressure 				( 0 )
	BrakeDistributorEmergencyApplicationRate 				( 20 )
	BrakeDistributorFullServicePressure 					( 55.114 )
	BrakeDistributorMaxAuxilaryResPressure 					( 72.5 )
	BrakeDistributorEmergencyResPressure 					( 72.5 )
	BrakeDistributorReleaseRate 						( 15 )
	BrakeDistributorApplicationRate 					( 20 )
	BrakeDistributorTrainPipeControlRatio 					( 2.27 )
	BrakeDistributorNormalFullReleasePressure 				( 72.5 )

	EmergencyResCapacity							( 3.604ft^3 )
	EmergencyResChargingRate						( 20.0 )
	EmergencyResVolumeMultiplier 						( 1.0 )

	ORTSBrakeShoeFriction ( 0.0 0.49 8.0 0.436 16.1 0.4 24.1 0.371 32.2 0.35 40.2 0.336 48.3 0.325 56.3 0.318 64.4 0.309 72.2 0.304 80.5 0.298 88.5 0.295 96.6 0.289 104.6 0.288 )
        Comment ( == COBRA Brakeshoes == )
        