
Comment ( *** Diesel Engine *** )
	Type ( Diesel )
	MaxPower ( 442kW )
	MaxForce ( 160kN )
	MaxContinuousForce ( 122kN )
	MaxVelocity ( 100kmh )

	MaxTemperature ( 85 )
	MaxOilPressure ( 71.12 )

Comment ( *** General *** )
	WheelRadius ( 0.55m )
	Sanding ( 25mph )
	NumWheels ( 4 )
	DoesHornTriggerBell ( 0 )
	ORTSDriveWheelWeight ( 64.7t )

Comment ( *** Electric Motor *** )
	MaxCurrent ( 1500A )
	