
	DoesBrakeCutPower( 1 )
	DoesHornTriggerBell( 0 )
	RunUpTimeToMaxForce ( 30 )
	BrakeCutsPowerAtBrakeCylinderPressure ( 15 )
	MaxSandingTime( 1200 )

	MaxDieselLevel ( 2976l )
	DieselUsedPerHourAtMaxPower ( 372l )
	DieselUsedPerHourAtIdle ( 4.5l )

	DieselEngineIdleRPM( 350 )
	DieselEngineMaxRPM( 1500 )
	DieselEngineSpeedOfMaxTractiveEffort( 17.3mph )
	DieselEngineMaxRPMChangeRate( 57 )

	EngineBrakesControllerDirectControlExponent( 1 )

 	ORTS ( ORTSWheelSlipCausesThrottleDown ( 1 ) )
	ORTS ( ORTSEmergencyCausesPowerDown    ( 0 ) )
 	ORTS ( ORTSEmergencyCausesThrottleDown ( 1 ) )

 	CabView ( v90.cvf )
	HeadOut (  -1.0 3.7 6.6 )
