
    	Description (
	"CP 1200 Series diesel-electric locomotive\n"+
	"Build by Brissoneau in 1961-1964\n"+
	"Locomotive number 1222 in orange livery\n"+
	"25 units were build (1201-1225)\n"+
	"Skin made by Johnny Red Productions, Portugal\n"+
	"Model by L'Auto-Rail\n"+
	"Locomotive power: 600cv\n\n"+
	"Mechanic Parts: Sorefame (Portugal)\n"+
	"Max Speed: 80 Km/h\n"+
	"Weight: 64 metric tons"
    	)
    	