
  	Sound (	"GenFreightWag1.sms" )
	Lights	(	1
			Light	(
			comment( rear red light )
			Type		( 0 )
			Conditions	(
				Service ( 2 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0 )
					LightColour ( 80ff0000 )
					Position ( -0.45 1.15 -7.91 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 1.0 )
				)
			)
		)
	)
	