
    Description (
	"This locomotive bears the name Entroncamento, after the Portuguese town\n"+
	"It is the first of it's series\n\n"+
	"In 1991 the national railway company of Portugal,Caminhos de Ferro Portugueses (CP), ordered 30 engines from Siemens which were identical to the 75 examples ordered by Spanish Renfe, except that they were single voltage locomotives.\n"+
	"Most of them were build under license by Sorefame in Portugal.\n"+
 	"Today they haul passenger trains through most of the electrified itineraries and also manyfreight trains indluding the coal trains from Sines to Pego.\n\n"+
	"Locomotive type: Siemens high-speed electric locomotive\n"+
	"Power: 5,600 kw\n"+
	"Max. speed: 220 km/h\n"+
	"Height: 3.431 m\n"+
	"Width: 3 m\n"+
	"Length: 20.38 m\n"+
	"Weight: 87.3 tons\n"+
	"Initial tractive effort: 300kn\n"
	)
	