
Comment ( *************** Brakes - Wagon Section - General ********************** )
	BrakeEquipmentType				( Distributor, Auxilary_reservoir, Handbrake )
	BrakeSystemType					( Air_twin_pipe )
	MaxBrakeForce					( 80.169kN )
	MaxHandbrakeForce 				( 21.378kN )

	TripleValveRatio				( 2.83 )
	MaxReleaseRate					( 0.51bar/s )   #( 0.39-0.51 )
	MaxApplicationRate				( 2bar/s )  #( 1.59-2.34 )
	MaxAuxilaryChargingRate				( 1.38bar/s )

	BrakeCylinderPressureForMaxBrakeBrakeForce	( 3.8bar )
	BrakePipeVolume 				( 18l ) #( calculado em coalstonewcastle.com.au )

	EmergencyResCapacity				( 75l )
	EmergencyResChargingRate			( 1.38bar/s )
	EmergencyResVolumeMultiplier 			( 1 )
	EmergencyBrakeResMaxPressure			( 5bar )
	