
Comment ( *** Diesel Engine SCANIA Vabis D802/1 *** )
    	Type					( Diesel )
	MaxPower				( 176.52kW )	Comment (* comprovado a partir ficha técnica de 1983 *)
	MaxForce				( 29.41995kN )	Comment (* comprovado a partir ficha técnica de 1983 *)
	MaxContinuousForce			( 6.619kN )	Comment (* comprovado a partir ficha técnica de 1983 *)
  	MaxVelocity				( 100kmh )	Comment (* comprovado a partir ficha técnica de 1983 *)

	ORTSDieselEngineMaxPower 		( 300hp )	Comment (* comprovado em manual de condução *)
	MaxTemperature				( 80 )		Comment (* comprovado em manual de condução 75 a 80º C*)
	MaxOilPressure				( 85.34 )	Comment (* comprovado em manual de condução 4,5 a 6,0 Kg/cm^2*)
	MaxDieselLevel				( 400l )	Comment (* comprovado a partir ficha técnica de 1983 *)
	DieselUsedPerHourAtMaxPower		( 40 )		Comment (* calculado a partir ficha técnica de 1983 *)
  	DieselUsedPerHourAtIdle			( 8 )		Comment (* comprovado a partir ficha técnica de 1983 *)

	DieselEngineIdleRPM 			( 600 )		Comment (* comprovado em manual de condução*)
	DieselEngineMaxRPM			( 1900 )	Comment (* comprovado em ficha técnica*)
	DieselEngineMaxRPMChangeRate		( 140 )
	DieselEngineSpeedOfMaxTractiveEffort	( 54kmh )

Comment ( *** General *** )
	WheelRadius				( 0.35m )
	Sanding					( 15kmh )
	NumWheels				( 4 )
	ORTSDriveWheelWeight			( 35t )

Comment ( *** Electric Motor *** )
	MaxCurrent				( 1000A )
	