
	DoesBrakeCutPower( 1 )
	DoesHornTriggerBell( 0 )
	RunUpTimeToMaxForce ( 30 )
	BrakeCutsPowerAtBrakeCylinderPressure ( 15 )
	MaxSandingTime( 1200 )

	DieselSmokeEffectInitialMagnitude( 1.7 )
	DieselSmokeEffectMaxMagnitude( 2.2 )
	DieselSmokeEffectInitialSmokeRate( 0.2 )
	DieselSmokeEffectMaxSmokeRate( 10 )

	EngineBrakesControllerDirectControlExponent( 1 )

 	ORTS ( ORTSWheelSlipCausesThrottleDown ( 1 ) )
	ORTS ( ORTSEmergencyCausesPowerDown    ( 0 ) )
 	ORTS ( ORTSEmergencyCausesThrottleDown ( 1 ) )
 	