
	Description (
	"Série 0106 da Argentina, cor Azul;\n\n"+
	"Automotoras a gasóleo série 0100. Cosntruídas na Suécia pela NOHAB entre 1947 e 949, entraram ao serviço em 1948. Serviram sempre toda a região do Alentejo bem como o Ribatejo e Algarve.\n"+
	"Tipo de tracção: Diesel-hidráulica;\n"+
        "Motor Diesel: Saab-Scania D11-01 A11"+
	"Potência Nominal (rodas): 185KW 252cv\n"+
	"Velocidade máxima: 100 km/h;\n"+
	"Disposição dos Rodados: 1A A1\n"+
	"Diâmetro das rodas (novas): 700 mm\n"+
	"Ano da entrada em serviço: 1948;\n"+
	"Ano da saída do serviço: 2005;\n"+
	"Bitola: 1668mm;\n"+
	"Projecto feito por Sérgio Pinto."
	)
