
Comment ( Standard ORTS Diesel Engine for CP 1400 English Electric )
Comment ( *** Diesel Engine *** )
	Type 				( Diesel )
	MaxPower 			( 713kW ) Comment (* 970cv comprovado em manual de conducao de 1969*)
	MaxForce 			( 161kN ) Comment (* comprovado em ficha técnica nº7 ed1987*)
	MaxContinuousForce 		( 142kN ) Comment (* comprovado em ficha técnica nº7 ed1987*)
	MaxVelocity 			( 105kmh ) Comment (* comprovado em ficha técnica nº7 ed1987*)
	ORTSContinuousForceTimeFactor 	( 3600 )
	MaxTemperature 		       ( 93.3degC ) Comment (* comprovado em manual de conducao*)
	MaxOilPressure 		       ( 59.738psi ) Comment (* 4,2 kg.cm2 comprovado em manual de conducao*)

	MaxDieselLevel 			( 2250l ) Comment (* comprovado em manual de conducao*)
	DieselEngineSpeedOfMaxTractiveEffort( 11.806mph ) Comment (* comprovado em ficha técnica nº7 ed1987*)
	DieselEngineType 		( electric )

Comment ( *** General *** )
	WheelRadius 			( 0.475m ) Comment (* comprovado em ficha técnica nº7 ed1987*)
	Sanding 			( 25mph )
	NumWheels 			( 4 )
	DoesHornTriggerBell 		( 0 )
	ORTSDriveWheelWeight 		( 64.4t ) Comment (* comprovado em ficha técnica nº7 ed1987*)

Comment ( *** Electric Motor *** )
	MaxCurrent 			( 1000A ) Comment (* comprovado em manual de conducao*)
	