
	DoesBrakeCutPower( 1 )
	DoesHornTriggerBell( 0 )
	RunUpTimeToMaxForce ( 30 )
	DieselEngineSpeedOfMaxTractiveEffort ( 30kmh )
	BrakeCutsPowerAtBrakeCylinderPressure ( 15 )
	MaxSandingTime( 1200 )

	ORTSCircuitBreaker( Manual )
	ORTSCircuitBreakerClosingDelay( 6s )
	ORTSPowerOnDelay( 1s )
	ORTSAuxPowerOnDelay( 2s )

 	ORTS ( ORTSWheelSlipCausesThrottleDown ( 1 ) )
	ORTS ( ORTSEmergencyCausesPowerDown    ( 0 ) )
 	ORTS ( ORTSEmergencyCausesThrottleDown ( 1 ) )

	CabView ( CP4700.cvf )
	HeadOut ( -1.7 3.0 7.75 )
	ORTSCircuitBreaker ( Manual )
