
	Lights	( 4
		Light	(
			comment( red light bright )
			Type		( 0 )
			Conditions	(
				Service ( 2 )
				Headlight ( 4 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.15 1.75 -10.45 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 1.0 )
					)
				)
			)
		Light	(
			comment( red light bright )
			Type		( 0 )
			Conditions	(
				Service ( 2 )
				Headlight ( 4 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.15 1.75 -10.45 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 1.0 )
					)
				)
			)
		Light	(
			comment( red light bright )
			Type		( 0 )
			Conditions	(
				Service ( 2 )
				Headlight ( 4 )
				Unit ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.15 1.75 10.45 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 1.0 )
					)
				)
			)
		Light	(
			comment( red light bright )
			Type		( 0 )
			Conditions	(
				Service ( 2 )
				Headlight ( 4 )
				Unit ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.15 1.75 10.45 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 1.0 )
					)
				)
			)
		)
		