
	Sound ( "genpasswagmodern.sms" )
	Lights	(	12
		Light	(
			comment( cola lofm reducido inferior derecha )
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.052 1.42 -13.06 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.9 )
				)
			)
		)
		Light	(
			comment( cola lofm reducido inferior izquierda )
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.052 1.42 -13.06 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.9 )
				)
			)
		)
		Light	(
			comment( cola lofm pleno inferior derecha )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.052 1.42 -13.06 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.9 )
				)
			)
		)	
		Light	(
			comment( cola lofm pleno inferior izquierda )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.052 1.42 -13.06 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.9 )
				)
			)
		)	
		Light	(
			comment( cola lfm reducido inferior derecha )
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.052 1.42 13.06  )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.9 )
				)
			)
		)
		Light	(
			comment( cola lfm reducido inferior izquierda )
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.052 1.42 13.06  )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.9 )
				)
			)
		)
		Light	(
			comment( cola lfm pleno inferior derecha )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.052 1.42 13.06 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.9 )
				)
			)
		)	
		Light	(
			comment( cola lfm pleno inferior izquierda )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.052 1.42 13.06 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.9 )
				)
			)
		)	
		Light	(
			comment( alarma lfm derecha )
			Type		( 0 )
			Conditions	(
				Unit ( 0 )
				Penalty ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.455 3.066 -11.767 )
					Azimuth ( 90 90 90 )
					Transition ( 0 )
					Radius ( 0.45 )
				)
			)
		)
		Light	(
			comment( alarma lfm izquierda )
			Type		( 0 )
			Conditions	(
				Unit ( 0 )
				Penalty ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.455 3.066 -11.767 )
					Azimuth ( -90 -90 -90 )
					Transition ( 0 )
					Radius ( 0.45 )
				)
			)
		)
		Light	(	
			comment( Camas libres derecha )
			Type ( 0 )
			Conditions (
				Unit ( 0 )
				)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle	( 0 )
			States	( 1
				State	(
					Duration ( 0.0 )
					LightColour ( 50b0327c )
					Position ( 1.45 1.911 -11.23)
					Azimuth (  90.0 90.0 90.0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
		Light	(	
			comment( Camas libres izquierda )
			Type ( 0 )
			Conditions (
				Unit ( 0 )
				)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle	( 0 )
			States	( 1
				State	(
					Duration ( 0.0 )
					LightColour ( 50b0327c )
					Position ( -1.45 1.911 -11.42)
					Azimuth (  -90.0 -90.0 -90.0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
	)		
