
Comment ( *** Electric Engine *** )
	Type			( Electric )
	MaxPower			( 2053kW )
	MaxForce			( 195kN )
	MaxContinuousForce		( 121.5kN )
	MaxVelocity			( 120kmh )

	MaxTemperature			( 120 )
	MaxOilPressure			( 90 )

Comment ( *** General *** )
	WheelRadius			( 0.650m )
	Sanding				( 25mph )
	NumWheels			( 4 )
	DoesHornTriggerBell		( 0 )
	ORTSDriveWheelWeight		( 72t )
	RunUpTimeToMaxForce	( 30 )
	DieselEngineSpeedOfMaxTractiveEffort ( 30kmh )

Comment ( *** Electric Motor *** )
	MaxCurrent			( 3000A )
	