
	Sound (	"..\\..\\sound\\pt_sound\\genptcar2.sms" )
      Lights	( 1
		Light	(
			comment( rear red light )
			Type		( 0 )
			Conditions	(
				Service ( 2 )
				Headlight ( 4 )
				Control ( 0 )
				Weather ( 0 )
				Coupling ( 0 )
				TimeOfDay ( 0 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -0.72 1.56 -6.68 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.3 )
				)
			)
		)
	)
		