
	DoesBrakeCutPower( 1 )
	DoesHornTriggerBell( 0 )
	RunUpTimeToMaxForce ( 30 )
	BrakeCutsPowerAtBrakeCylinderPressure ( 15 )
	MaxSandingTime( 1200 )

	DieselSmokeEffectInitialMagnitude ( 0.25 )
	DieselSmokeEffectMaxMagnitude ( 3.75 )
	DieselSmokeEffectInitialSmokeRate ( 4 )
	DieselSmokeEffectMaxSmokeRate ( 17 )

	DieselEngineIdleRPM ( 550 )
	DieselEngineMaxRPM ( 1050 )
	DieselEngineMaxRPMChangeRate ( 50 )

	EngineBrakesControllerDirectControlExponent( 1 )

 	ORTS ( ORTSWheelSlipCausesThrottleDown ( 1 ) )
	ORTS ( ORTSEmergencyCausesPowerDown    ( 0 ) )
 	ORTS ( ORTSEmergencyCausesThrottleDown ( 1 ) )
 	