
	Description (
	"Light train haulage configuration \n"+
	"These Diesel units were built in Canada, in 1979 by Bombardier (ex MLW) \n"+
	"At the beginningthey were used mainly in the Beira Alta to pull International trains \n"+
	"and freight trains and also in the Oeste Route for intercity services.\n"+
	"Today they are all operating in freight trains all over the country. \n"+
	"These are the most powerfull diesel locos, in Portugal.\n"+
	"Unit 1961 was destroyed in a colision in Alcafache on 11th September 1985.\n"+
	"Peace to the souls that died in what is considered the worst train accident in Portugal.\n"+
	"Total units built: 13.\n"+
	"Locomotive type: Diesel-Electric\n"+
	"Traction motor: One Bombardier 251/E V16\n"+
	"Power: 1655 kW(2,250 hp)\n"+
	"Max. speed: 120 km/h (74.5 mph).\n"+
	"Gear ratio: 81:22\n"+
	"Max. continuous tractive effort: 28.200 kg (62,170.35 lb)\n"+
	"Wheel configuration: Twelve 1016mm ( 40-in) diameter in Co-Co configuration.\n"+	
	"Gauge: 1668 mm"
	)
	