
    EngineOperatingProcedures (
	"To move forward\n"+
	"1.	Press the W key to move the Reverser to Forward.\n"+
	"2.	Press the ; (SEMICOLON) key to release the train brakes.\n"+
	"3.	Press the [ (LEFT BRACKET) key to release the locomotive brake.\n"+
	"4.	Press the D key to move the throttle from Idle to Notch 1.\n"+  
	"5.	Gradually increase power (D key), one notch at a time, until your train reaches the desired speed.\n\n"+
	"To slow the train\n"+
	"1.	Press the A key to move the throttle to a lower setting.\n"+
	"2.	Use the brakes to further reduce speed if desired.\n\n"+  
	"To apply the dynamic brakes\n"+
	"1.	Press the A key to move the throttle to the Idle position.\n"+
	"2.	Wait for 10 seconds, then press the . (PERIOD) key to advance the Dynamic Brake handle from Off to the Setup position.  After allowing a few seconds for braking circuit setup, press the . [PERIOD] key again to set the desired level of dynamic braking (Levels 1 - 8).\n\n"+
	"To release the dynamic brakes\n"+
	"1.	Press the D key to move the throttle towards Idle.\n\n"+
	"To apply the train brakes\n"+
	"1.	Press the ' (APOSTROPHE) key to apply the train brakes.\n\n"+
	"To bail off the train brakes on the locomotive\n"+
	"1. Press the / (FORWARD SLASH) key.\n\n"+
	"To release the train brakes\n"+
	"1. Press the ; (SEMICOLON) key to release the train brakes.\n\n"+
	"To apply the locomotive brake\n"+
	"1.	Press the ] (RIGHT BRACKET) key to apply the locomotive brake.\n\n"+
	"To release the locomotive brake\n"+
	"1. Press the [ (LEFT BRACKET) key to release the locomotive brake.\n\n"+
	"To activate emergency braking\n"+
	"1.	Press the A key to reduce the throttle to Idle.\n"+
	"2.	Press the BACKSPACE key to activate emergency braking.\n\n"+
	"To back up\n"+
	"1.	Bring your train to a full stop.\n"+ 
	"2.	Press the S key to move the Reverser to the Reverse position.\n"+
	"4.	Release the brakes.\n"+
	"5.	Slowly advance the throttle lever (D key).\n\n"+
	"To couple to a car or locomotive\n"+
	"1. Coast into the unit at a very slow speed, about 2 mph.\n"+
	"TIP: To use the Coupling view, press the 6 key.\n"+
	"2. Press F9 to open the Train Operations window.\n"+
	"3. If the icon for the unit you coupled to is red, the handbrake is on. Double-click the car to release the handbrake.\n"+
	"4. Close the Train Operations window.\n\n"+
	"To uncouple from a car or locomotive\n"+
	"1. Press F9 to open the Train Operations window.\n"+
	"2. Double-click a unit in the part of the train you want to uncouple from the locomotive, to set the handbrake.\n"+
	"3. Double-click the coupler between the units you want to uncouple and the rest of the train.\n"+
	"4. Close the Train Operations window."
    )
    