
    Description (
	"Broad-gauge Diesel Locomotive\n"+
	"The largest locomotive series in Portugal, with a total number of 67, built by English Electric, based on BR class 20.\n"+
	"Entered service in 1967, served in every type of service everywhere on the Portuguese broadgauge network.\n\n"+
	"Power: 1370 cv\n\n"+
	"Diesel Engine: 1 x 8CSVT\n\n"+
	"Traction motors: 4 x EE 548\n\n"+
	"V. Max: 105 Kph (65 mph)\n\n"+
	"Construction: 1967-1969\n\n"+
	"Service: 1467 - until this day"
    )
    