
    EngineOperatingProcedures (
    "To move forward\n"+
    "1. Press the P key to raise the pantograph\n"+
    "2. Press the O key to close the main circuit breaker. It will close when you hear it.\n"+
    "3.	Press the W key to move the Reverser to Forward.\n"+
    "4.	Press the ; (SEMICOLON) key to release the train brakes.\n"+
    "5.	Press the D key to move increase the throttle setting.\n\n"+  
    "To slow the train\n"+
    "1.	Press the A key to move the throttle to a lower setting.\n"+
    "2.	Use the brakes to further reduce speed if desired.\n\n"+   
    "To apply the train brakes\n"+
    "1.	Press the ' (APOSTROPHE) key to apply the train brakes.\n\n"+
    "To release the train brakes\n"+
    "1. Press the ; (SEMICOLON) key to release the train brakes.\n\n"+
    "To activate emergency braking\n"+
    "1.	Press the A key to reduce the throttle to Idle.\n"+
    "2.	Press the BACKSPACE key to activate emergency braking.\n\n"+
    "To back up\n"+
    "1.	Bring your train to a full stop.\n"+
    "2.	Press the S key to move the Reverser to the Reverse position.\n"+
    "3.	Press the ; (SEMICOLON)  to release the brakes.\n"+
    "4.	Slowly advance the throttle lever (D key).\n\n"+
    "To load and unload passengers\n"+
    "1. Stop at a station.\n"+
    "2. Press the ENTER key.\n"+
    "3. Wait for the 'permission to depart' signal.\n"+
    "TIP: Use the Next Station driving aid (F10) to monitor loading and unloading."
    )
     