
Comment (*** Brake Systems ***)
	BrakesTrainBrakeType( vacuum_single_pipe )
	ORTSBrakePipeTimeFactor ( 0.036s )
	TrainPipeLeakRate ( 0.04inHg/s )

Comment (*** Ejectors ***)
	VacuumBrakesHasVacuumPump ( 0 )
	ORTSBrakePipeChargingRate ( 0.32inHg/s )
	VacuumBrakesLargeEjectorUsageRate ( 600lb/h )
	VacuumBrakesSmallEjectorUsageRate ( 240lb/h )
	VacuumBrakesMinBoilerPressureMaxVacuum ( 90psi )


Comment (*** Brake Valve Combined ***)
	TrainBrakesControllerMaxSystemPressure ( 21inHg )
	ORTSBrakeEmergencyTimeFactor ( 5s )
