
 	Description (
 		"Desta série de locomotivas existiram doze em Portugal, originalmente com os numeros 61 a 72.\n"+ 
		"Foram construídas pela Compagnie Fives Lille entre 1899 e 1904.\n"+ 
		"Estas locomotivas eram muito semelhantes às construídas para a companhia Francesa The Nord Co.\n"+ 
		"No princípio, detinham os serviços nobres: os rápidos da Linha do Norte e Leste.\n"+ 
		"A partir de 1910 passaram a estar afectas ao depósito do Entroncamento acabando os seus serviços\n"+ 
		"na Beira Baixa e Leste em 1968 à excepção da 268 que foi destacada para o Minho e Douro e esteve no activo até 1970.\n"+ 
		"A 262 sobrevive exposta na Fernave, no Entroncamento.\n"
	)
    