
	EngineOperatingProcedures (
	"To move forward\n"+
	"1.	Press the W key several times to move the Reverser to full Forward.\n"+
	"2.	Press the ; (SEMICOLON) key to release the train brakes.\n"+
	"3.	Press the D key to increase the Regulator setting.\n"+  
	"4.	As you accelerate, press the S key to slowly reduce the Reverser setting, then adjust the Regulator to maintain the desired speed.\n\n"+
	"To slow the train\n"+
	"1.	Press the A key to move the Regulator to a lower setting.\n"+
	"2.	Use the brakes to further reduce speed if desired.\n\n"+
	"To apply the train brakes\n"+
	"1.	Press the ' (APOSTROPHE) key to apply the train brakes.\n"+
	"2. To hold the brakes at their current setting, lower the brake lever until it's in its middle (Neutral) position, by pressing the ; (SEMICOLON) key.\n\n"+
	"To release the train brakes\n"+
	"1. Press  the ; (SEMICOLON) key to release the train brakes.\n"+
	"2. When the brakes are released, raise the brake lever until it's in its middle (Neutral) position, by pressing the ' (APOSTROPHE) key.\n\n"+
	"To back up\n"+
	"1.	Bring your train to a full stop.\n"+ 
	"2.	Press the S key several times to move the Reverser to the full Reverse position.\n"+
	"4.	Press the ; (SEMICOLON) key to release the brakes.\n"+
	"5.	Slowly advance the regulator (D key).\n\n"+
	"To load and unload passengers\n"+
	"1. Stop at a station.\n"+
	"2. Press the ENTER key.\n"+
	"3. Wait for the \"permission to depart\" whistle.\n"+
	"TIP: Use the Next Station driving aid (F10) to monitor loading and unloading.\n\n"+
	"To couple to a car or locomotive\n"+
	"1. Coast into the unit at a very slow speed, about 2 mph.\n"+
	"TIP: To use the Coupling view, press the 6 key.\n"+
	"2. Press F9 to open the Train Operations window.\n"+
	"3. If the icon for the unit you coupled to is red, the handbrake is on. Double-click the car to release the handbrake.\n"+
	"4. Close the Train Operations window.\n\n"+
	"To uncouple from a car or locomotive\n"+
	"1. Press F9 to open the Train Operations window.\n"+
	"2. Double-click a unit in the part of the train you want to uncouple from the locomotive, to set the handbrake.\n"+
	"3. Double-click the coupler between the units you want to uncouple and the rest of the train.\n"+
	"4. Close the Train Operations window.\n\n"+
	"Firing commands (Automatic Fireman OFF in Options screen)\n"+
	"To add coal to the firebox\n"+
	"1. Press the F key to open the Firebox door.\n"+
	"2. Press the R key to increase the shoveling rate.\n\n"+
	"To stop adding coal to the fire\n"+
	"1. Press SHIFT+R to decrease the shoveling rate.\n"+
	"2. Press SHIFT+F to close the firebox door.\n\n"+
	"To operate the blower\n"+
	"1.	Press the N key to increase the blower.\n"+
	"2. Press SHIFT+N to decrease the blower.\n\n"+
	"To operate the dampers\n"+
	"1.	Press the M key to open the dampers.\n"+
	"2. Press SHIFT+M to close the dampers.\n\n"+
	"To inject water into the boiler\n"+
	"1.	Press the I key to turn on the steam to Injector 1.\n"+
	"(You can also press the O key to turn on the steam to Injector 2.)\n"+
	"2.	Press the K key to increase the water flow to Injector 1.\n"+
	"(To increase the water flow to Injector 2, press the L key.)\n\n"+
	"To stop boiler water injection\n"+ 
	"1. Press the I key to turn off the steam to Injector 1.\n"+
	"2. Press the O key to turn off the steam to Injector 2."
	)
     