
 	Sound		( CP261wag.sms )
Comment ( *** Lights *** )
	Lights	(	1	
		Light	(
			comment( Rear red light )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 1 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0 )
					LightColour ( 80ff0000 )
					Position ( 1.1 2.3 -2.4 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 1 )
				)
			)
		)
	)
