
	Description (
 		"Desta série de locomotivas existiram vinte em Portugal.\n"+ 
		"A Henschel & Sohn construiu as locomotivas 351 a 365 entre 1911 e 1913. A Societé Alsacienne de Constructions Mècaniques foi responsável pela construção das locomotivas 366 a 370 em 1906. Estas últimas resultam de uma transformação sendo originalmente numeradas de 301 a 305.\n"+ 
		"Foram as primeiras locomotivas em Portugal a utilizar o sistema compound, de 4 cilindros e vapor sobreaquecido.\n"+
		"Foram adquiridas especificamente para rebocarem os comboios rápidos da Linha do Norte - o Flecha de Prata - e também os comboios internacionais Lusitania Expresso e o Sud-Express.\n"+ 
		"A partir de 1910 passaram a estar afectas ao depósito do Entroncamento acabando os seus serviços\n"+ 
		"o fim da sua vida, a partir dos anos 60 foi passado no depósito do Barreiro a rebocarem comboios de passageiros para Beja e Funcheira..\n"+ 
		"A 359 foi responsável por um acidente na estação de lisboa-Rossio.\n"+
		"A 357 esteve muito tempo expostana Fernave, no Entroncamento e agora está preservada no Museu da mesma cidade."
	)
