
Effects(
	SpecialEffects(
		Comment(* Steam Heating Leak *)
		HeatingHoseFX		( 0.0 0.6 -3.7 0 1 0 0.16 )
		Comment (* Water Scoop - RHS *)
		WaterScoopFX 		( 0.25 0.1 -0.25 1.0 0.1 0 0.5 )
		Comment (* Water Scoop - LHS *)
		WaterScoopFX 		( -0.25 0.1 -0.25 -1.0 0.1 0 0.5 )
		Comment (* Tender Water Overflow - RH vent *)
		TenderWaterOverflowFX 	( 1.0 3.10 1.50 0 -1 0 0.2 )
		Comment (* Tender Water Overflow - LH vent *)
		TenderWaterOverflowFX 	( -1.0 3.10 1.50 0 -1 0 0.2 )
		Comment (* Tender Water Overflow - tank filler *)
		TenderWaterOverflowFX 	( 0 3.10 -2.9 0 0.7 -0.3 0.5 )
	)
)
	