
Comment ( *** Electric Engine *** )
Comment (	Type ( Control )  ) #(not yet fully functional. when functionall all other lines in this inc files, after this one should be erased )

	Type ( Electric )
	MaxPower ( 0kW )
	MaxForce ( 0kN )
	MaxContinuousForce ( 0kN )
	MaxVelocity ( 90kmh )

	MaxTemperature ( 120 )
	MaxOilPressure ( 90 )

Comment ( *** General *** )
	WheelRadius ( 0.420m )
	Sanding ( 25mph )
	NumWheels ( 4 )
	DoesHornTriggerBell ( 0 )
	ORTSDriveWheelWeight ( 42.60t )

Comment ( *** Electric Motor *** )
	MaxCurrent ( 1000A )
	
	