
	DoesBrakeCutPower					( 1 )
	DoesHornTriggerBell				( 0 )
	RunUpTimeToMaxForce				( 30 )

	ORTSCircuitBreaker				( manual )
	ORTSCircuitBreakerClosingDelay		( 2s )
	ORTSPowerOnDelay					( 1s )
	ORTSAuxPowerOnDelay				( 3s )

 	ORTS (
		ORTSWheelSlipCausesThrottleDown	( 0 )
		ORTSEmergencyCausesPowerDown 		( 0 )
		ORTSEmergencyCausesThrottleDown	( 1 )
	)

 	ORTS ( ORTSWheelSlipCausesThrottleDown ( 1 ) )
 	ORTS ( ORTSEmergencyCausesThrottleDown ( 1 ) )

	HeadOut ( -1.7 2.7 10.25 )
