
    Description (
	"Locotractor diesel Drewry serie 1000\n"+
	"Estas unidades foram as primeiras a gasoleo na CP.\n"+
	"Construidas pela Drewry Car Co. , entraram ao servico em 1948 numa epoca em que haviam serias dificuldades em manter as locomotivas a vapor em funcionamento devido a escassez de carvao.\n"+
	"There were a total of 6 of these engines entering service since 1948, making service at Campanha, Sta Apolonia and Barreiro.\n"+
 	"Motor Diesel de Traccão: Gardner 8L3 200hp.\n"+
 	"Potencia nominal nas rodas: 150hp.\n"+
 	"V Max.: 41.5 kph.\n"+
  	"Peso em O.M.: 30.4 metric tons."
   )
   