
	Description (
	" The 1300 diesel-electric locomotive started it's service in 1952 with a green and silver livery.\n"+
	" CP bought a total of 12 of these locomotives, in sequence of the second phas of the "Plan Marshall". They first severd in the Sintra Line, doing suburban service. They also served in the North Line but only between Lisboa and Gaia. They were not fitted to cross the D. Maria bridge, and therefore they were never seen in the north of Portugal.\n"+
	" Other prestigious services include the traction of the "Sud-Express".\n"+
	" With the comming of english electric material (1400  and 1800) and electrification of the North Line, these locomotives were sent to the southern regions of Portugal.\n"+
	" In the begining of the 70's all of them were on Alentejo and Algarve, until the end of their days.\n"+
	"In late 1985 only the 1304 was in service and it was a short time since it was put aside. Today, only one is preserved in original CP livery, for the museum - the 1311.\n"+
	"Locomotive type: Diesel-Electric\n"+
	"Power source: Two CC 1604-D Generator\n"+
	"Power: 1020 hp by 4 362-RZ tracion engines\n"+
	"Max. speed: 134 kmh\n"+
	"Gear ratio: 65:18\n"+
	"Diesel Engine: Two Superior 40 B-Lx with 6 Lv cilinders\n"+
	"Max. continuous tractive effort: 11.140 kg\n"+
	"Wheel configuration: Six 1.016 m wheels in A1A A1A configuration\n"+
	"Height: 4.300 m\n"+
	"Weight: 95,40 ton\n"+
	"Length: 17,060 m\n"+
	"Width: 3,050 m"
    	)
    	