
	Sound ( "k31eng.sms" )
	Lights ( 4
		Light (
			comment ( Luz Traz Vermelha Esquerda Minima )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 3 )
			)
			FadeIn ( 0.2 )
			FadeOut ( 0.2 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( 55FF0000 )
					Position ( -0.779 1.528 -12.437 )
					Azimuth ( 180 180 180 )
					Elevation ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
		Light (
			comment ( Luz Traz Vermelha Direita Minima )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 3 )
			)
			FadeIn ( 0.2 )
			FadeOut ( 0.2 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( 55FF0000 )
					Position ( 0.779 1.528 -12.437 )
					Azimuth ( 180 180 180 )
					Elevation ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
		Light (
			comment ( Luz Traz Vermelha Esquerda Maxima )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 3 )
			)
			FadeIn ( 0.2 )
			FadeOut ( 0.2 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( FFFF0000 )
					Position ( 0.779 1.528 -12.437 )
					Azimuth ( 180 180 180 )
					Elevation ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
		Light (
			comment ( Luz Traz Vermelha Direita Maxima )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 3 )
			)
			FadeIn ( 0.2 )
			FadeOut ( 0.2 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( FFFF0000 )
					Position ( -0.779 1.528 -12.437 )
					Azimuth ( 180 180 180 )
					Elevation ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
	)
	