
	Description (
		"These Diesel units CP 0400 are built in 1965/66 by SOREFAME,and it was the first generation of stainless steel-budied DMU´s.\n\n" +
		"It was refurbish in 1997 from old class CP 0400.\n\n" +
		"The class have always ben used in the Minho and Douro route,and made the international Oporto<>Salamanca by Douro route.\n\n" +
		"but today they are scattered through operating Regional and International Oporto<>Vigo.\n\n" +
		"Diesel Engine: 1 Rolls Royce motor and hydraulic transmission.\n\n" +
		"Max. speed: 120 km/h.\n\n" +
		"Total units built: 19.\n\n" +
		"All units operating on CP USGP.\n\n" +
		"Gauge: 1668 mm"
	)
	