
Comment ( *** Vaccum Brakes - Wagon Section *** )
	BrakeEquipmentType 				( Vacuum_brake, Handbrake, Auxilary_reservoir )
	BrakeSystemType 					( Vacuum_single_pipe )
	MaxBrakeForce					( 306.701kN ) Comment ( calculado em coalstonewcastle.com.au tara Empty weight - 83.4t, NBR - 0.75, Friction - 0.5 )
	MaxHandbrakeForce					( 81.787kN )  Comment ( calculado em coalstonewcastle.com.au tara Empty weight - 83.4t, NBR - 0.75, Friction - 0.5 )
	
	BrakeCylinderPressureForMaxBrakeBrakeForce 	( 21.0inHg )
	BrakePipeVolume 					( 36.25l ) Comment ( calculado em coalstonewcastle.com.au tara Car Lenght - 54.498ft Vacuum )
	ORTSNumberBrakeCylinders 			( 2 )
	ORTSBrakeCylinderSize 				( 18in )
	ORTSAuxilaryResCapacity 			( 3.24ft^3 )
	MaxReleaseRate					( 40inHg/s )
	MaxApplicationRate				( 34inHg/s )
	ORTSDirectAdmissionValve 			( 0 )
	ORTSBrakeShoeFriction (
		0.0 0.50
		8.0 0.288
		16.1 0.241
		24.1 0.211
		32.2 0.187
		40.2 0.173
		48.3 0.161
		56.3 0.150
		64.4 0.142
		72.2 0.139
		80.5 0.134
		88.5 0.129
		96.6 0.125
		104.6 0.123
		112.7 0.121
	)
	Comment ( Cast Iron Brakeshoes )
