
Comment ( *************** Brakes - Wagon Section - General ********************** )
	BrakeEquipmentType 					( Distributor, Auxilary_reservoir, Handbrake )
	BrakeSystemType						( Air_twin_pipe )
	MaxBrakeForce						( 306.701kN ) Comment ( calculado em coalstonewcastle.com.au tara Empty weight - 83.4t, NBR - 0.75, Friction - 0.5 )
	MaxHandbrakeForce						( 81.787kN )  Comment ( calculado em coalstonewcastle.com.au tara Empty weight - 83.4t, NBR - 0.75, Friction - 0.5 )

	TripleValveRatio						( 2.83 )
	MaxReleaseRate						( 0.62bar/s )
	MaxApplicationRate					( 1.59bar/s )
	MaxAuxilaryChargingRate					( 1.38bar/s )

	BrakeCylinderPressureForMaxBrakeBrakeForce 	( 3.8bar )
	BrakePipeVolume 						( 14.2l ) Comment ( calculado em coalstonewcastle.com.au )

	EmergencyResCapacity					( 60l )
	EmergencyResChargingRate				( 1.38bar/s )
	EmergencyResVolumeMultiplier 				( 1.0 )

	ORTSBrakeShoeFriction (
		0.0 0.50
		8.0 0.288
		16.1 0.241
		24.1 0.211
		32.2 0.187
		40.2 0.173
		48.3 0.161
		56.3 0.150
		64.4 0.142
		72.2 0.139
		80.5 0.134
		88.5 0.129
		96.6 0.125
		104.6 0.123
		112.7 0.121
	)
	Comment ( Cast Iron Brakeshoes )
