
Comment (* Standard ORTS Diesel Engine for CP 1550 English Electric *)
Comment ( ***Diesel Engine MLW/Alco 251 C3 V12  *** )
	Type 					( Diesel )
      MaxPower				( 1251kW )
	MaxForce 				( 243kN ) Comment (* comprovado em ficha técnica nº10 ed1987*)
	MaxContinuousForce 		( 193kN ) Comment (* comprovado em ficha técnica nº10 ed1987*)
	MaxVelocity 			( 120kmh ) Comment (* comprovado em ficha técnica nº10 ed1987*)
	ORTSContinuousForceTimeFactor ( 1800 )
  	MaxTemperature 			( 93degC )
	MaxOilPressure 			( 59.738psi )

	MaxDieselLevel 			( 3929l ) Comment (* comprovado documento técnico 1983*)
	DieselEngineSpeedOfMaxTractiveEffort( 17.3mph )
	DieselEngineType 			( electric )
	ORTSSpeedOfMaxContinuousForce ( 22.5kmh )

Comment ( *** General *** )
	WheelRadius 			( 0.508m ) Comment (* comprovado em ficha técnica nº10 ed1987*)
	Sanding 				( 25mph )
	NumWheels 				( 6 )  Comment (* 6 eixos motores *)
	ORTSDriveWheelWeight 		( 89.7t ) Comment (* comprovado em ficha técnica nº10 ed1987*)

Comment ( *** Traction Characteristics 6 x GE-761 92:19*** )
	MaxCurrent 				( 1500A )
	ORTSElectricTrainSupply ( Mode ( Unfitted ))




	




