
	DoesBrakeCutPower( 1 )
	DoesHornTriggerBell( 0 )
	RunUpTimeToMaxForce ( 30 )
	BrakeCutsPowerAtBrakeCylinderPressure ( 15 )
	MaxSandingTime( 1200 )

	EngineBrakesControllerDirectControlExponent( 1 )
	DoesHornTriggerBell ( 0 )

	AntiSlip ( 0 )
 	ORTS ( ORTSWheelSlipCausesThrottleDown ( 1 ) )
	ORTS ( ORTSEmergencyCausesPowerDown    ( 0 ) )
 	ORTS ( ORTSEmergencyCausesThrottleDown ( 1 ) )

 	CabView ( sd402.cvf )
	HeadOut (  1.25 2.8 8.3 )
