
    	Description (
	"The 1550 diesel-electric locomotive, a popular and versatile performer capable of tasks ranging "\n+
	"from passenger to freight trains over the main line.\n"+
	"Locomotive type: Diesel-Electric\n"+
	"Power source: Diesel engine\n"+
	"Power: 1,700 hp\n"+
	"Max. speed: 75 mph (115 km/h)\n"+
	"Gear ratio: 92:19\n"+
	"Traction motors: One 251 C 3, MLW/ALCO\n"+
	"Max. continuous tractive effort: 19.300 kg\n"+
	"Wheel configuration: Six 1.016 m wheels in Co' Co' configuration\n"+
	"Height: 4.356 m\n"+
	"Weight: 89,7 ton\n"+
	"Length: 17,905 m\n"+
	"Width: 2,997 m"
    	)
    	