
    	Sound (	"..\\sound\\pt_sound\\genptwag2.sms" )
	Lights	(	1
			Light	(
			comment( Rear red light )
			Type		( 0 )
			Conditions	(
				Service ( 2 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0 )
					LightColour ( 80ff0000 )
					Position ( -1.03 2.109 -6.56 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 1.0 )
				)
			)
		)
	)
	