
	Mass ( 32t ) Comment (* tara 28t *)
Comment ( *** Estimated - Bogies WL or Arbel Fox ***)
Comment ( *** Curve Resistance & SuperElevation ***)
	CentreOfGravity ( 0.0m 1.2m 0.0m )
	ORTSTrackGauge ( 1m 668mm )
	ORTSRigidWheelbase ( 2m 500mm )
	ORTSUnbalancedSuperelevation ( 180mm )

Comment ( ********** Derailment Coefficient **********)
	ORTSLengthBogieCentre ( 10.294m )
	ORTSLengthCarBody ( 16.20m )
	ORTSLengthCouplerFace ( 17.5m )
	ORTSNumberAxles ( 4 )
	ORTSNumberBogies ( 2 )
	ORTSWheelFlangeLength ( 19.151mm )
	ORTSMaximumWheelFlangeAngle ( 62deg )

Comment( *** Friction / Adhesion *** )
	ORTSAdhesion ( ORTSSlipWarningThreshold ( 70 ) )
	ORTSAdhesion (	Wheelset (
			Axle (
				ORTSInertia ( 1167 )
				ORTSRadius ( 0.520m )
			)
		)
	)
	ORTSBearingType ( Roller )
 	Comment (Friction Calculator - Goods Wagon - Older Carriages and Vans - 32;2,684;3,937;12,61;4 )
	ORTSDavis_A ( 525.92 )
	ORTSDavis_B ( 11.30 )
	ORTSDavis_C ( 1.67 )

	ORTSStandstillFriction ( 583.497469 )
	ORTSMergeSpeed ( 0.211585 )
	ORTSBearingType ( Roller )
	ORTSAntislip ( 0 )

	DerailRailHeight ( 4cm )
	DerailRailForce ( 160kN )
	DerailBufferForce ( 400kN )
	