
    EngineOperatingProcedures (
		"To ocupy the cabin\n"+
		"1. Press ENTER to activate the Master Key. You will light the monitor.\n"+
		"2. Press the P key to raise the pantograph.\n"+
		"3. Press the O key (and keep it pressed) to close the main circuit breaker. It will close when you hear it.\n"+
		"To move forward\n"+
		"1.	Press the W key to move the Reverser to Forward.\n"+
		"2.	Press the ; (SEMICOLON) key to release the train brakes.\n"+
		"3.	Press the D key to move increase the throttle setting.\n\n"+  
		"To slow the train\n"+
		"1.	Press the A key to move the throttle to a lower setting.\n"+
		"2.	Use the brakes to further reduce speed if desired.\n\n"+   
		"To apply the train brakes\n"+
		"1.	Press the ' (APOSTROPHE) key to apply the train brakes.\n\n"+
		"To release the train brakes\n"+
		"1. Press the ; (SEMICOLON) key to release the train brakes.\n\n"+
		"To activate emergency braking\n"+
		"1.	Press the A key to reduce the throttle to Idle.\n"+
		"2.	Press the BACKSPACE key to activate emergency braking.\n\n"+
		"To back up\n"+
		"1.	Bring your train to a full stop.\n"+
		"2.	Press the S key to move the Reverser to the Reverse position.\n"+
		"3.	Press the ; (SEMICOLON)  to release the brakes.\n"+
		"4.	Slowly advance the throttle lever (D key).\n\n"+
		"To load and unload passengers\n"+
		"1. Stop at a station.\n"+
		"2. Loading and unloading is automatic.\n"+
		"3. Wait for the 'permission to depart' signal.\n"+
		"To use Cruise Control\n"+
		"1. Press SHIFT+D to increase target speed.\n"+
		"2. Press D to increase the throttle setting to maximum.\n"+
		"3. Use SHIFT+A to decrease target speed.\n"+
		"4. Use At+Shift+A to set selected speed to 0.\n"
	)
     