
	Lights ( 10
		Light (
			comment ( Sphere of light )
			Type ( 1 )
			Conditions (
				Headlight ( 2 )
				Unit ( 2 )
			)
			FadeIn ( 0.1 )
			FadeOut ( 0.1 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( FFFFFFFF )
					Position ( 0 0.3 5 )
					Angle ( 15 )
					Transition ( 1 )
					Radius ( 200 )
				)
			)
		)
		Light (
			comment ( Sphere of light )
			Type ( 1 )
			Conditions (
				Headlight ( 3 )
				Unit ( 2 )
			)
			FadeIn ( 0.1 )
			FadeOut ( 0.1 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( FFFFFFFF )
					Position ( 0 0.3 5 )
					Angle ( 25 )
					Transition ( 1 )
					Radius ( 400 )
				)
			)
		)
		Light (
			comment ( Head light Left1 Soft )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 2 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( 80FFFFFF )
					Position ( -0.835 1.55 11.15 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
		Light (
			comment ( Head light Right1 Soft )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 2 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( 80FFFFFF )
					Position ( 0.835 1.55 11.15 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.5 )
				)
			)
		)
		Light (
			comment ( Traz Left )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 3 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( FFFF0000 )
					Position ( -0.89 1.75 -11.1 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.3 )
				)
			)
		)
		Light (
			comment ( Traz Right )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 3 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( FFFF0000 )
					Position ( 0.89 1.75 -11.1 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.3 )
				)
			)
		)
		Light (
			comment ( Traz Left1 )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 3 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( FFFF0000 )
					Position ( -0.89 1.75 -11.1 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.3 )
				)
			)
		)
		Light (
			comment ( Traz Right1 )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 3 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( FFFF0000 )
					Position ( 0.89 1.75 -11.1 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.3 )
				)
			)
		)
		Light (
			comment ( Head light Left1 Hard )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 2 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( FFFFFFFF )
					Position ( -0.7 1.63 11.2 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.75 )
				)
			)
		)
		Light (
			comment ( Head light Right1 Hard )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 2 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( FFFFFFFF )
					Position ( 0.7 1.63 11.2 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.75 )
				)
			)
		)
	)
	