
Comment ( *** Diesel Engine *** )
	Type ( Diesel )
	MaxPower ( 570kW )
	MaxForce ( 111.8kN )
	MaxContinuousForce ( 74.5kN )
	MaxVelocity ( 120kmh )

	MaxTemperature ( 93 )
	MaxOilPressure ( 59.738 )
	MaxDieselLevel ( 460 ) 
	DieselUsedPerHourAtMaxPower ( 130 )
	DieselUsedPerHourAtIdle ( 10 )

	DieselEngineIdleRPM ( 450 ) 
	DieselEngineMaxRPM ( 1500 ) 
	DieselEngineMaxRPMChangeRate ( 140 )
	DieselEngineSpeedOfMaxTractiveEffort ( 33kmh )

	ORTSContinuousForceTimeFactor ( 3600 )
	ORTSSpeedOfMaxContinuousForce ( 63kph )

Comment ( *** General *** )
	WheelRadius ( 0.460m )
	Sanding ( 15kph )
	NumWheels ( 4 )
	ORTSDriveWheelWeight ( 32.665t )
