
	Description (
	"These Diesel units were built in 1979 by SOREFAME.\n"+
	"They served, among others, in the Intercity of Beira Alta,\n"+
	"but soon they were scattered through operating regional\n"+
	"trains in Douro, oeste and Algarve, and some suburban trains in Lisbon and Oporto.\n"+
	"This series has be taken from service and scraped with the exception of one unit, preserved for museology.\n\n"+
	"Diesel Engine: 2 x SFAC, type SDHRI, 6LH, 550 hp each at 1500 rpm\n\n"+
	"Max. speed: 120 km/h\n\n"+
	"Gauge: 1668 mm"
	)
	