
    	Sound (	"..\\sound\\pt_sound\\genptcar1.sms" )
	Lights	( 2	
		Light	(
			comment( red light )
			Type		( 0 )
			Conditions	(
				Headlight ( 0 )
				Control ( 0 )
				Weather ( 0 )
				TimeOfDay ( 0 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.030 2.109 -13.06 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 1.0 )
					)
				)
			)
		Light	(
			comment( red light )
			Type		( 0 )
			Conditions	(
				Headlight ( 0 )
				Control ( 0 )
				Weather ( 0 )
				TimeOfDay ( 0 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.03 2.109 -13.06 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 1.0 )
					)
				)
			)
		)
		