
	EngineOperatingProcedures ( "Operación del vehículo\n"+
        "1. Pulsa la tecla B para arrancar el motor.\n"+
	"2. Pulsa la tecla W para mover el Inversor a Adelante.\n"+
	"3. Pulsa la tecla Ñ para liberar los frenos del tren.\n"+
	"4. Pulsa la tecla E para meter la primera marcha.\n"+
	"5. Pulsa la tecla D para aumentar la potencia mediante el Regulador.\n"+  
	"6. Incrementa la potencia gradualmente (tecla D) poco a poco y pulsa E para cambiar de marchas hasta alcanzar la velocidad deseada.\n\n"+

	"Para ralentizar la velocidad\n"+
	"1. Pulsa la tecla A para disminuir la potencia con el Regulador.\n"+
	"2. Usa los frenos para reducir la velocidad a la deseada.\n"+  
	"3. Pulsa las teclas Shift + E para reducir las marchas.\n\n"+
	
	"Para aplicar los frenos del tren\n"+
	"1. Pulsa la tecla ' (apóstrofe) para aplicar los frenos del tren.\n\n"+

	"Para liberar los frenos del tren\n"+
	"1. Pulsa la tecla Ñ para liberar los frenos del tren.\n\n"+
	
	"Para activar el freno de emergencia\n"+
	"1. Pulsa la tecla A para reducir la potencia al ralentí.\n"+
	"2. Pulsa la tecla BACKSPACE para activar el freno de emergencia.\n\n"+

	"Para invertir la marcha\n"+
	"1. Detén completamente el tren.\n"+ 
	"2. Libera los frenos.\n"+
        "3. Pulsa 1 para volver a la vista de cabina.\n"+
        "4. Pulsa F9 para abrir la ventana Operaciones del Tren.\n"+
        "5. Pulsa con el ratón sobre la unidad del otro extremo de la composición.\n"+
        "6. Pulsa 1 para pasar a la cabina del otro extremo del tren.\n\n"+

	"Para enganchar un vagón ó locomotora\n"+
	"1. Lleva la unidad a una velocidad lenta, sobre 4 km/h.\n"+
	"   Truco: usa la vista de enganche (tecla 6).\n"+
	"2. Pulsa F9 para abrir la ventana Operaciones del Tren.\n"+
	"3. Si el icono de la unidad que deseas enganchar está en rojo, el freno de mano está activado. Doble clic en la unidad para liberarlo.\n"+
	"4. Cierra la ventana de Operaciones del Tren (F9).\n\n"+

	"Para desenganchar un vagón ó locomotora\n"+
	"1. Pulsa la tecla F9 para abrir la ventana Operaciones del Tren.\n"+
	"3. Haz doble clic en el icono del enganche para desenganchar ésa unidad del resto del tren.\n"+
	"4. Cierra la ventana Operaciones del Tren (F9)." ) 
)
