
	Description (
 	"Estas locomotivas 2-8-4T construidas em 1924 pela Henschel & Sohn vieram para Portugal como compensação na Primeira Grande Guerra. Eram 10, originalmente com a numeração 401-410, depois quando passaram para o Sul e Sueste em 1927 voltaram a mudar de numeração para 01201-01210 e finalmente em 1947 receberma a numeração 0181-0190.\n"+
	"Eram locomotivas para tráfego misto e eram mais leves e menos potentes que uma versão similar entregue em 1923. Foram usadas em ramais no Sul de Portugal e nos anos 60 foram transferidas para o Entroncamento e para o Porto. Sofreram entretanto alterações - foram adicionadas as cupulas para areia, a chaminé foi substituida e foram alteradas para queimar óleo. A 0187 foi a ultima a circular até 25 de Março de 1977.\n\n"+
	"Características\n"+
	"Distribuição: Walschaert\n"+
	"Peso: 98t\n"+
	"Diametro Rod. motor: 1350mm\n"+
	"Diametro cilindro: 530mm\n"+
	"Curso dos embolos: 660mm\n"+
	"Esforço de Tracção: 10877kgf\n"+
	"Timbre da Caldeira: 12 Kg/cm2\n"+
	"Velocidade máxima: 90km/h (est.)"
	)
