
Comment ( *************** Brakes - Wagon Section - General ********************** )
	BrakeEquipmentType 				( "Handbrake, Vacuum_brake, Auxilary_reservoir" )
	BrakeSystemType 				( "Vacuum_single_pipe" )


	ORTSNumberCarBrakeShoes				( 16 )
	ORTSBrakeShoeType				( "Cast_Iron_P6" )


	MaxReleaseRate 					( 5.0inHg/s )
	MaxApplicationRate 				( 5.0inHg/s )

	BrakeCylinderPressureForMaxBrakeBrakeForce 	( 21inHg ) Comment (* not yet functional *)

	ORTSDirectAdmissionValve 			( 1 )
	ORTSAuxiliaryResCapacity 			( 5.76ft^3 )
	ORTSNumberBrakeCylinders 			( 2 )


