
Comment ( *************** Freio Ar comprimido UIC - twin pipe ********************** )
	BrakeEquipmentType				( "Distributor, auxiliary_reservoir, Handbrake" )
	BrakeSystemType					( "Air_twin_pipe" )


	ORTSNumberCarBrakeShoes				( 16 )
	ORTSBrakeShoeType				( "Cast_Iron_P10" )

	TripleValveRatio				( 2.83 )
	MaxReleaseRate					( 0.62bar/s )
	MaxApplicationRate				( 1.59bar/s )
	MaxAuxilaryChargingRate				( 1.38bar/s )
	BrakeCylinderPressureForMaxBrakeBrakeForce 	( 55.114 )

	ORTSDirectAdmissionValve			( 0 )
	ORTSAuxiliaryResCapacity			( 20 )
	ORTSNumberBrakeCylinders 			( 2 )

	ORTSWheelBrakeSlideProtection 			( 0 )
	ORTSWheelBrakesSlideProtectionLimitDisable 	( 0 )

	EmergencyResVolumeMultiplier 			( 1.0 )
	EmergencyResChargingRate			( 1.38bar/s )
	EmergencyResCapacity				( 60l )
