
Comment ( *** Carruagens de 1ª classe 19-22 034 a 038 - ficha 31 ***)
	Size 				( 3.1m 4.05m 26.12m )
	InertiaTensor 		( Box (3m 4m 26m) )
	Mass 				( 41t ) Comment (* tara 37t *)
	WheelRadius 		( 0.425m )
	ORTSLengthBogieCentre 	( 16.820m )
	ORTSLengthCarBody 	( 24.820m )
	ORTSLengthCouplerFace 	( 26.120m )

	MaxBrakeForce		( 333kN ) Comment (* 34tf *)
	MaxHandbrakeForce 	( 186kN ) Comment (* 19tf *)
	BrakePipeVolume 		( 0.73ft^3 )
	PassengerCapacity 	( 54 )

	Comment (Friction Calculator - Passenger Carriage - European UIC 1960+ - 41;3,016;3,935;25,48;4 )
	ORTSDavis_A 		( 433.32 )
	ORTSDavis_B 		( 14.47 )
	ORTSDavis_C 		( 1.03 )
	DerailRailForce 		( 205kN )

