
Comment ( *** Carruagens Restaurante 88-40 001 a 002 - ficha 52 ***)
	Size 			( 3.1m 4.05m 26.625m )
	InertiaTensor 		( Box (3m 3.5m 26m) )
	Mass 			( 43t ) Comment (* tara 42,5t *)
	ORTSLengthBogieCentre 	( 19.0m )
	ORTSLengthCarBody 	( 26.620m )
	ORTSLengthCouplerFace 	( 25.320m )

	PassengerCapacity 	( 2 )

	Comment (Friction Calculator - Passenger Carriage - European UIC 1960+ - 43;3,016;3,935;25,98;4 )
	ORTSDavis_A ( 444 )
	ORTSDavis_B ( 15.2 )
	ORTSDavis_C ( 1.05 )
	DerailRailForce ( 240kN )


	ORTSFreightAnims (
                WagonEmptyWeight ( 43t )
		LoadingAreaLength ( 25.32 )
            	Offset ( 0 0 0 )
            	IntakePoint ( 0 6.0 Container )
	)

