
Comment ( *** Carruagens de 2ª classe 21-40 001 a 024 - ficha 44 ***)
Comment ( *** Carruagens de 2ª classe 21-40 025 a 030 - ficha 44A ***)
	Size 				( 3.016m 3.935m 26.62m )
	InertiaTensor 		( Box (3m 3.5m 26m) )
	Mass 				( 52t ) Comment (* tara 46.5t *)
	WheelRadius 		( 0.460m )
	ORTSLengthBogieCentre 	( 19.0m )
	ORTSLengthCarBody 	( 25.320m )
	ORTSLengthCouplerFace 	( 26.620m )

	PassengerCapacity 	( 88 )

	Comment (Friction Calculator - Passenger Carriage - European UIC 1960+ - 52;3,016;3,935;25,98;4 )
	ORTSDavis_A 		( 488 )
	ORTSDavis_B 		( 18.36 )
	ORTSDavis_C 		( 1.05 )
	DerailRailForce 		( 260kN )

