
Comment ( *** Carruagens de 1ª classe 10-69 001 a 028 - ficha 40 ***)
	Size 				( 3.016m 3.935m 26.62m )
	InertiaTensor 		( Box (3m 3.5m 26m) )
	Mass 				( 46t ) Comment (* tara 42.5t *)
	WheelRadius 		( 0.425m )
	ORTSLengthBogieCentre 	( 19.0m )
	ORTSLengthCarBody 	( 25.320m )
	ORTSLengthCouplerFace 	( 26.620m )

	PassengerCapacity 	( 60 )

	Comment (Friction Calculator - Passenger Carriage - European UIC 1960+ - 46;3,016;3,935;25,98;4 )
	ORTSDavis_A 		( 448.89 )
	ORTSDavis_B 		( 15.53 )
	ORTSDavis_C 		( 1.05 )
	DerailRailForce		( 220kN )

