
Comment ( *** Carruagens de 1ª classe com Bar 84-22 003 a 008 - ficha 32 ***)
	Size 				( 3.06m 3.903m 26.12m )
	InertiaTensor 		( Box (3m 3.5m 26m) )
	Mass 				( 42t ) Comment (* tara 37t *)
	WheelRadius 		( 0.425m )
	ORTSLengthBogieCentre 	( 16.820m )
	ORTSLengthCarBody 	( 24.820m )
	ORTSLengthCouplerFace 	( 26.120m )

	PassengerCapacity 	( 42 )

	Comment (Friction Calculator - Passenger Carriage - European UIC 1960+ - 42;3,016;3,935;25,48;4 )
	ORTSDavis_A 		( 438.57 )
	ORTSDavis_B 		( 14.83 )
	ORTSDavis_C 		( 1.03 )
	DerailRailForce 		( 210kN )

