
Comment ( *** Carruagens de 1ª classe 19-22 012 a 033 - ficha 20 ***)
	Size ( 3.1m 4.05m 26.6m )
	Mass ( 46t ) Comment (* tara 44t *)
	ORTSLengthBogieCentre ( 19.0m )
	ORTSLengthCarBody ( 26.620m )
	ORTSLengthCouplerFace ( 25.320m )

	PassengerCapacity ( 58 )

	Comment (Friction Calculator - Passenger Carriage - Corail - 46;3,016;3,97;25,98;4 )
	ORTSDavis_A ( 458.98 )
	ORTSDavis_B ( 12.42 )
	ORTSDavis_C ( 0.69 )
	DerailRailForce ( 230kN )

	ORTSFreightAnims (
                WagonEmptyWeight ( 41t )
		LoadingAreaLength ( 24.82 )
            	Offset ( 0 0 0 )
            	IntakePoint ( 0 6.0 Container )
	)
