
Comment ( *** Carruagens de 2ª classe 22-40 001 a 080 - ficha 43 ***)
	Size 			( 3.1m 4.05m 26.625m )
	InertiaTensor 		( Box (3m 3.5m 26m) )
	Mass 			( 48t ) Comment (* tara 42,5t *)
	ORTSLengthBogieCentre 	( 19.0m )
	ORTSLengthCarBody 	( 26.620m )
	ORTSLengthCouplerFace 	( 25.320m )620m )

	PassengerCapacity 	( 96 )

	Comment (Friction Calculator - Passenger Carriage - European UIC 1960+ - 48;3,016;3,935;25,98;4 )
	ORTSDavis_A ( 468.85 )
	ORTSDavis_B ( 16.94 )
	ORTSDavis_C ( 1.05 )
	DerailRailForce ( 240kN )


	ORTSFreightAnims (
                WagonEmptyWeight ( 48t )
		LoadingAreaLength ( 25.32 )
            	Offset ( 0 0 0 )
            	IntakePoint ( 0 6.0 Container )
	)

