
Comment ( *** Carruagens de 1ª e 2ª classes 30-69 001 a 009 - ficha 41 ***)
	Size 				( 3.016m 3.935m 26.62m )
	InertiaTensor 		( Box (3m 3.5m 26m) )
	Mass 				( 46t ) Comment (* tara 42t *)
	WheelRadius 		( 0.425m )
	ORTSLengthBogieCentre 	( 19.000m )
	ORTSLengthCarBody 	( 25.320m )
	ORTSLengthCouplerFace 	( 26.620m )

	PassengerCapacity 	( 72 )

	Comment (Friction Calculator - Passenger Carriage - European UIC 1960+ - 46;3,016;3,935;25,98;4 )
	ORTSDavis_A 		( 458.98 )
	ORTSDavis_B 		( 16.24 )
	ORTSDavis_C 		( 1.05 )
	DerailRailForce 		( 230kN )