
Comment ( *** Carruagens Restaurante 88-50 001 a 003 - ficha 25 ***)
	Size 				( 3.06m 3.903m 26.12m )
	InertiaTensor 		( Box (3m 3.5m 26m) )
	Mass 				( 43t ) Comment (* tara 40t *)
	WheelRadius 		( 0.425m )
	ORTSLengthBogieCentre 	( 18.120m )
	ORTSLengthCarBody 	( 24.820m )
	ORTSLengthCouplerFace 	( 26.120m )

	PassengerCapacity 	( 40 )

	Comment (Friction Calculator - Passenger Carriage - European UIC 1960+ - 43;3,016;3,935;25,48;4 )
	ORTSDavis_A 		( 443.76 )
	ORTSDavis_B 		( 15.18 )
	ORTSDavis_C 		( 1.03 )
	DerailRailForce		( 215kN )

