
	Sound (	"1520eng.sms" )
	Lights ( 7
		Light (
			comment( Sphere of light )
			Type		( 1 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 2 )
				)
			Cycle	( 0 )
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( 0 3.298 7.39547 )
					Transition ( 0 )
					Radius ( 400.0 )
					Angle ( 15.0 )
				)
			)
		)
		Light (
			comment( Front light DIM )
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 2 )
				)
			Cycle	( 0 )
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( 0 3.21 7.40747 )
					Transition ( 0 )
					Radius ( 1 )
				)
			)
		)
		Light (
			comment( Front light bright )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 2 )
				)
			Cycle	( 0 )
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( ffffffff )
					Position ( 0 3.21 7.41947 )
					Transition ( 0 )
					Radius ( 1 )
				)
			)
		)
		Light (
			comment( Rear red light left)
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 3 )
				)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle	( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -0.95 1.76 -8.1 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
		Light (
			comment( Rear red light right)
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 3 )
				)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle	( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.05 1.76 -8.1 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
		Light (
			comment( Rear red light left)
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 3 )
				)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle	( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -0.95 1.76 -8.1 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
		Light (
			comment( Rear red light right)
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 3 )
				)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle	( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.05 1.76 -8.1 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.4 )
				)
			)
		)
	)
	