
Comment ( *** General Information *** )
	WheelRadius ( 0.508m )
	Sanding ( 25mph )
	NumWheels ( 6 )
	ORTSDriveWheelWeight ( 84t )

Comment ( *** Diesel Prime Mover (Engine) *** )
	Type ( Diesel )
	ORTSDieselEngineMaxPower ( 751kW )
	MaxDieselLevel( 1180g-uk )
	MaxTemperature ( 120degF )
	MaxOilPressure ( 90 )
	DieselUsedPerHourAtMaxPower ( 75.2g-uk )
	DieselUsedPerHourAtIdle ( 25.5g-uk )
	DieselEngineIdleRPM( 450 )
	DieselEngineMaxRPM( 850 )
	DieselEngineMaxRPMChangeRate( 40 )


Comment ( *** Traction Motor *** )
	MaxPower ( 1560hp )
	MaxForce ( 209.79kN )
	MaxContinuousForce ( 193.25kN )
	ORTSSpeedOfMaxContinuousForce ( 19.5mph )
	MaxVelocity ( 120kmh )
	MaxCurrent ( 1500A )
	