
Comment ( *** Diesel Engine *** )
	Type ( Diesel )
	MaxPower ( 751kW )
	MaxForce ( 209.79kN )
	MaxContinuousForce ( 193.25kN )
	MaxVelocity ( 120kmh )

	MaxTemperature ( 86 )
	MaxOilPressure ( 85.34 )

Comment ( *** General *** )
	WheelRadius ( 0.508m )
	Sanding ( 25mph )
	NumWheels ( 6 )
	DoesHornTriggerBell ( 0 )
	ORTSDriveWheelWeight ( 84t )

Comment ( *** Electric Motor *** )
	MaxCurrent ( 1500A )
	