
	DoesBrakeCutPower( 1 )
	DoesHornTriggerBell( 0 )
	RunUpTimeToMaxForce ( 30 )
	BrakeCutsPowerAtBrakeCylinderPressure ( 15 )
	MaxSandingTime( 1200 )

	MaxDieselLevel ( 2976l )
	DieselUsedPerHourAtMaxPower ( 372l )
	DieselUsedPerHourAtIdle ( 4.5l )

	DieselEngineIdleRPM( 400 )
	DieselEngineMaxRPM( 1100 )
	DieselEngineSpeedOfMaxTractiveEffort( 17.3mph )
	DieselEngineMaxRPMChangeRate( 47 )

	EngineBrakesControllerDirectControlExponent( 1 )

 	ORTS ( ORTSWheelSlipCausesThrottleDown ( 1 ) )
	ORTS ( ORTSEmergencyCausesPowerDown    ( 0 ) )
 	ORTS ( ORTSEmergencyCausesThrottleDown ( 1 ) )

 	CabView ( gp38.cvf )
	HeadOut ( -1.7 3.1 3.5 )
