
    	Description (
	"The CP 1320 Series diesel-electric locomotive, was used only in freigth trains. 18 of these locomotives were bought by CP (in 1989), from RENFE (Spanish Railways)(was the RENFE 1300 Series, now RENFE 313 Series).\n"+
	"Locomotive type: Diesel-Electric DL 535 TeS\n"+
	"Multiple Units Formation: up to 4 Locomotives\n"+
	"Power: 1,010 hp\n\n"+
	"Max. speed: 62.5 mph (100 km/h)\n"+
	"Gear ratio: 92:12\n"+
	"Power source: Diesel engine\n"+
	"Diesel Engine: ALCO 251-D1, 1370 CV, 1100 rpm\n"+
	"Continuous Electric Power Generator: GT 581 E\n"+
	"Traction motors: Six GE761 DC electric motors\n"+
	"Max. starting tractive effort: 20,979 kg\n"+
	"Max. continuous tractive effort: 19,300 kg\n"+
	"Wheel configuration: Twelve 20-inch (51 cm) diameter in Co-Coconfiguration (two sets of three "+
	"driven axles)\n"+
	"Pneumatic Dual Brake: Air and Vacuum\n"+
	"Dynamic Brake: Reostatic\n"+
	"Height: 4 m\n"+
	"Weight: 83.915 metric tons\n"+
	"Length: 16 m\n"+
	"Width: 2.8 m"
    	)
    	