
	Effects	(
		DieselSpecialEffects (
				Exhaust1 (
					0.245 4.30 -2.475
					0 1 0
					0.1
				)
				Exhaust2 (
					0.341 4.30 -2.475
					0 1 0
					0.1
				)
				Exhaust3 (
					0.437 4.30 -2.475
					0 1 0
					0.1
				)
				Exhaust4 (
					0.245 4.30 -2.565
					0 1 0
					0.1
				)
				Exhaust5 (
					0.437 4.30 -2.565
					0 1 0
					0.1
				)
			)
        	)
	ExhaustColor ( aaeaf9ff )
	ExhaustTransientColor ( 4082dfff )

Comment ( *** Diesel Engine - Exhaust Effects *** )
	DieselSmokeEffectInitialMagnitude( 1.7 )
	DieselSmokeEffectMaxMagnitude( 2.2 )
	DieselSmokeEffectInitialSmokeRate( 0.2 )
	DieselSmokeEffectMaxSmokeRate( 10 )

	