
Comment ( *************** Freio Ar comprimido UIC - twin pipe ********************** )
	BrakeEquipmentType				( Distributor, Auxilary_reservoir, Handbrake )
	BrakeSystemType					( Air_twin_pipe )
	MaxBrakeForce					( 51kN )
	MaxHandbrakeForce					( 17kN )

	BrakePipeVolume 					( 0.74ft^3 )
	TripleValveRatio					( 2.83 )
	MaxReleaseRate					( 0.62bar/s )
	MaxApplicationRate				( 1.59bar/s )
	MaxAuxilaryChargingRate				( 1.38bar/s )

	BrakeCylinderPressureForMaxBrakeBrakeForce	( 3.5bar )


	EmergencyResCapacity				( 60l )
	EmergencyResChargingRate			( 1.38bar/s )
	EmergencyResVolumeMultiplier 			( 1.0 )
	EmergencyBrakeResMaxPressure			( 5bar )

	Comment (ORTSBrakeShoeFriction ( 0.0 0.49 8.0 0.436 16.1 0.4 24.1 0.371 32.2 0.35 40.2 0.336 48.3 0.325 56.3 0.318 64.4 0.309 72.2 0.304 80.5 0.298 88.5 0.295 96.6 0.289 104.6 0.288) )
	