
Comment ( *** Diesel Engine *** )
	Type ( Diesel )
	MaxPower ( 354kW )
	MaxForce ( 195kN )
	MaxContinuousForce ( 116kN )
	MaxVelocity ( 120kmh )

	MaxTemperature ( 93 )
	MaxOilPressure ( 59.738 )
	MaxDieselLevel ( 264gal )
	DieselUsedPerHourAtMaxPower ( 17.3gal )
	DieselUsedPerHourAtIdle ( 3.2gal )


	ORTSContinuousForceTimeFactor ( 3600 )
	ORTSSpeedOfMaxContinuousForce ( 63kph )

	DieselEngineIdleRPM( 315 )
	DieselEngineMaxRPM( 1400 )
	DieselEngineSpeedOfMaxTractiveEffort( 13mph )
	DieselEngineMaxRPMChangeRate( 40 )
 	DieselEngineType ( mechanical )

 	GearBoxNumberOfGears( 6 )
 	GearBoxDirectDriveGear( 6 )
 	GearBoxMaxSpeedForGears( 19 39 55 68 90 106 )
 	GearBoxMaxTractiveForceForGears( 156KN 130KN 113KN 100KN 89KN 65KN )
 	GearBoxOverspeedPercentageForFailure( 170 )
 	GearBoxBackLoadForce( 5000 )
 	GearBoxCoastingForce( 2000 )
 	GearBoxUpGearProportion( 0.85 )
 	GearBoxDownGearProportion( 0.35 )
 	GearBoxOperation( manual )
 	GearBoxEngineBraking( all_gears )


Comment ( *** General *** )
	WheelRadius ( 0.460m )
	Sanding ( 15kph )
	NumWheels ( 4 )
	ORTSDriveWheelWeight ( 32.665t )
