
	DoesBrakeCutPower( 1 )
	DoesHornTriggerBell( 0 )
 	RunUpTimeToMaxForce ( 15 )
	BrakeCutsPowerAtBrakeCylinderPressure ( 15 )
	MaxSandingTime( 1200 )

	ExhaustColor ( aaeaf9ff )
	ExhaustTransientColor ( 4082dfff )
	DieselSmokeEffectInitialMagnitude ( 0.6 )
	DieselSmokeEffectMaxMagnitude ( 2.2 )
	DieselSmokeEffectInitialSmokeRate ( 0.9 )
	DieselSmokeEffectMaxSmokeRate ( 4.8 )

	EngineBrakesControllerDirectControlExponent( 1 )

	AntiSlip ( 0 )
 	ORTS ( ORTSWheelSlipCausesThrottleDown ( 1 ) )
	ORTS ( ORTSEmergencyCausesPowerDown    ( 0 ) )
 	ORTS ( ORTSEmergencyCausesThrottleDown ( 1 ) )

	CabView ( CP0500.cvf )