
	Description (
 	"Three FIAT trainsets were built for CP and entered service in 1953.\n"+
	"Their first service was to connect Lisbon to Oporto in just 4H20.The service name was "Foguete".\n"+
	"Later, in 1966 with electrification of the North Line, BB2500 electric locomotives started to take this service and Fiat 500 was reasigned.\n"+
	"They were assigned to make the fast "Sotavento" trains from Barreiro to Vila Real de Santo António, in Algarve".\n"+
	"Power source: OM-SBD diesel engine, 12 cilinder in two rows\n"+
	"Motive Power: 480 hp\n"+
	"Max. speed: 120 km/h (75 mph)\n"+
	"Weight: 170 tons (187 US tons)"
	)
	