
	EngineOperatingProcedures (
	"To move forward\n"+
	"1.	Press Shift+E if necessary to move the Speed Gear handle to neutral.\n"+
	"2. Hold down the A key as necessary to move the Throttle to 0%.\n"+
	"3.	Press the W key to move the Reverser to Forward.\n"+
	"4. Press E to move the Speed Gear handle to 1.\n"+
	"5.	Hold down the ; (SEMICOLON) key to release the train brakes.\n"+
	"6.	Press the D key to move increase the Throttle setting.\n\n"+  
	"To coast\n"+
	"1.	Hold down the A key to reduce the Throttle to 0%.\n"+
	"2.	Press Shift+E to move the Speed Gear handle from 1 to Neutral.\n\n"+
	"To resume powered operation\n"+
	"1.	If traveling under 50 km/h, press E once to move the Speed Gear handle to 1. If traveling over 50 km/h, press E twice to move the Speed Gear handle to 2.\n"+
	"2.	Press the D key to advance the Throttle.\n\n"+
	"To operate the FIAT 500 gear box:\n"+
	"1.	Press the E key to move the Speed Gear handle to 2.\n"+
	"2.	Press the D key to advance the Throttle.\n"+
	"3.   IMPORTANT NOTE: Before moving the Speed Gear handle to the next positon, bring Throtlle to 0%.\n\n"+
	"To slow the train\n"+
	"1.	Press the A key to move the Throttle to a lower setting.\n"+
	"2.	Use the brakes to further reduce speed if desired.\n\n"+
	"To apply the train brakes\n"+
	"1.	Hold down the ' (APOSTROPHE) key.\n\n"+
	"To release the train brakes\n"+
	"1. Hold down the ; (SEMICOLON) key.\n\n"+
	"To operate the Engine Brake\n"+
	"1.	Press Shift+E to move the Speed Gear handle to 2.\n"+
	"2.	Hold down the A key to move the Throttle to 0%.\n"+
	"3.	Press the P key to activate the Engine Brake.\n\n"+
	"To deactivate the Engine Brake\n"+
	"1.	Press the D key to advance the Throttle.\n\n"+
	"To back up\n"+
	"1.	Bring your train to a full stop.\n"+
	"2. Hold down the A key to move the Throttle to 0%.\n"+
	"3. Press Shift+E to move the Speed Gear handle to Neutral.\n"+
	"4.	Press the S key twice to move the Reverser to the Reverse position.\n"+
	"5.	Press the ; [SEMICOLON] key to release the brakes.\n"+
	"6. Press E to move the Speed Gear handle to 1.\n"+
	"7.	Press the D key to slowly advance the Throttle.\n\n"+
	"To load and unload passengers\n"+
	"1. Stop at a station.\n"+
	"2. Press the Enter key.\n"+
	"3. Wait for the \"permission to depart\" buzzer.\n"+
	"TIP: Use the Next Station driving aid (F10) to monitor loading and unloading.\n\n"+
	"To couple to a car or locomotive\n"+
	"1. Coast into the unit at a very slow speed, about 4 km/h.\n"+
	"Tip: To use the Coupling view, press the 6 key.\n"+
	"2. Press F9 to open the Train Operations window.\n"+
	"3. If the icon for the unit you coupled to is red, the handbrake is on. Double-click the car to release the handbrake.\n"+
	"4. Close the Train Operations window.\n\n"+
	"To uncouple from a car or locomotive\n"+
	"1. Press F9 to open the Train Operations window.\n"+
	"2. Double-click a unit in the part of the train you want to uncouple from the locomotive, to set the handbrake.\n"+
	"3. Double-click the coupler between the units you want to uncouple and the rest of the train.\n"+
	"4. Close the Train Operations window."
	)
	