
	Sound ( "cpalsthomeng.sms" )
	Lights ( 4
		Light (
			comment ( Red light right Minima )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 3 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( 55FF0000 )
					Position ( -0.567 1.764 -8.839 )
					Azimuth ( -180 -180 -180 )
					Elevation ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.45 )
				)
			)
		)
		Light (
			comment ( Red light left Minima )
			Type ( 0 )
			Conditions (
				Headlight ( 2 )
				Unit ( 3 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( 55FF0000 )
					Position ( 0.567 1.764 -8.839 )
					Azimuth ( -180 -180 -180 )
					Elevation ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.45 )
				)
			)
		)
		Light (
			comment ( Red light right maxima )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 3 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( FFFF0000 )
					Position ( -0.567 1.764 -8.839 )
					Azimuth ( -180 -180 -180 )
					Elevation ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.85 )
				)
			)
		)
		Light (
			comment ( Red light left Maxima )
			Type ( 0 )
			Conditions (
				Headlight ( 3 )
				Unit ( 3 )
			)
			FadeIn ( 0.5 )
			FadeOut ( 0.5 )
			Cycle ( 0 )
			States ( 1
				State (
					Duration ( 0 )
					LightColour ( FFFF0000 )
					Position ( 0.567 1.764 -8.839 )
					Azimuth ( -180 -180 -180 )
					Elevation ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.85 )
				)
			)
		)
	)
	