
	DoesBrakeCutPower				( 0 )
	DoesHornTriggerBell			( 0 )
	RunUpTimeToMaxForce 			( 30 )
	BrakeCutsPowerAtBrakeCylinderPressure ( 15 )
	MaxSandingTime				( 1200 )

	MaxDieselLevel 				( 1321gal )
	DieselUsedPerHourAtMaxPower 		( 168gal )
	DieselUsedPerHourAtIdle 		( 13.2gal )

	DieselSmokeEffectInitialMagnitude 	( 3.0 )
	DieselSmokeEffectInitialSmokeRate 	( 1.8 )
	DieselSmokeEffectMaxMagnitude 	( 4.0 )
	DieselSmokeEffectMaxSmokeRate 	( 5.0 )

	DieselEngineIdleRPM 			( 550 )
	DieselEngineMaxRPM 			( 1350 )
	DieselEngineMaxRPMChangeRate 		( 40 )
	DieselEngineSpeedOfMaxTractiveEffort( 17.3mph )

	EngineBrakesControllerDirectControlExponent( 1 )

 	ORTS ( ORTSWheelSlipCausesThrottleDown ( 1 ) )
	ORTS ( ORTSEmergencyCausesPowerDown    ( 0 ) )
 	ORTS ( ORTSEmergencyCausesThrottleDown ( 1 ) )
