
	Description (
		"The CP1900 series is a based on the french SNCF CC72000 series.\n\n" +
		"Locomotive type: Diesel-Electric\n\n" +
		"Power source: SACM-AGO V12 DSHR  152.1l\n\n" +
		"Power: 2,260 hp\n\n" +
		"Dynamic brake: No\n\n" +
		"Max. speed: 120 Kph\n\n" +
		"Alternator: AT53\n\n" +
		"Traction motors: Six TAO659\n\n" +
		"Max. TE: 388 kN\n\n" +
		"Max. continuous TE: 251 kN\n\n" +
		"Wheel configuration: Co Co\n\n" +
		"Weight: 116.5 metric tons"
	)
	