
	Description (
		"The CP1900 series is a based on the french SNCF CC72000 series.\n\n" +
		"Locomotive type: Diesel-Electric\n\n" +
		"Power source: SACM-AGO V12 DSHR  152.1l\n\n" +
		"Power: 2,260 hp\n\n" +
		"Dynamic brake: Yes\n\n" +
		"Max. speed: 100 Kph\n\n" +
		"Alternator: AT53\n\n" +
		"Traction motors: Six TAO659\n\n" +
		"Max. TE: 39,600 kg\n\n" +
		"Max. continuous TE: 25,600 kg\n\n" +
		"Wheel configuration: Co Co\n\n" +
		"Weight: 117 metric tons"
	)
	