
      Description (
		"These units were buitl in 1954/55 by - N. V. Allan & Co - Netherlands -  for the Portuguese Railways.\n"+ 
      	"Class: My 301 to 325 and Ry 301 to 312\n"+
		"Locomotive type: Diesel - Electric\n"+
		"Diesel Engine: 2 x POYAUD C 6150T of 240 hp at 1800 rpm\n"+
		"Power: 252 kW ( 343 hp )\n"+
		"Max. speed: 100 km/h\n"+
		"Height: 4.25 m\n"+
		"Width: 3.17 m\n"+
		"Length: 23.63 m\n"+
		"Weight: 56.5 tons ( 51.5 tare )\n"+
		"Wheel configuration: Bo' Bo'\n"+
      	"Gauge: 1668 mm\n"+
      	"Allan railcars operate commuter trains around Coimbra - to Serpins and Figueira da Foz via Pampilhosa \n"+
		"and regional trains on Beira Baixa Line and Oeste Line."
	)
	