
  	Sound ( "genpasswagmodern.sms" )
Lights	(	12
		Light	(
			comment( cola lfm reducido derecha )
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.13 3.055 -12.72  )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.45 )
				)
			)
		)
		Light	(
			comment( cola lfm reducido izquierda )
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.09 3.055 -12.72  )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.45 )
				)
			)
		)
		Light	(
			comment( cola lfm reducido inferior )
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.052 1.42 -12.72 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.9 )
				)
			)
		)
		Light	(
			comment( cola lfm pleno derecha )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.13 3.055 -12.72 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.45 )
				)
			)
		)
		Light	(
			comment( cola lfm pleno izquierda )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.09 3.055 -12.72 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.45 )
				)
			)
		)
		Light	(
			comment( cola lfm pleno inferior )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 3 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.052 1.42 -12.72 )
					Azimuth ( -180 -180 -180 )
					Transition ( 0 )
					Radius ( 0.9 )
				)
			)
		)	
		Light	(
			comment( cola lofm reducido derecha )
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.13 3.055 12.72  )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.45 )
				)
			)
		)
		Light	(
			comment( cola lofm reducido izquierda )
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.09 3.055 12.72  )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.45 )
				)
			)
		)
		Light	(
			comment( cola lofm reducido inferior )
			Type		( 0 )
			Conditions	(
				Headlight ( 2 )
				Unit ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.052 1.42 12.72  )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.9 )
				)
			)
		)
		Light	(
			comment( cola lofm pleno derecha )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( 1.13 3.055 12.72 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.45 )
				)
			)
		)
		Light	(
			comment( cola lofm pleno izquierda )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.09 3.055 12.72 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.45 )
				)
			)
		)
		Light	(
			comment( cola lofm pleno inferior )
			Type		( 0 )
			Conditions	(
				Headlight ( 3 )
				Unit ( 2 )
			)
			FadeIn	( 0.5 )
			FadeOut	( 0.5 )
			Cycle		( 0 )
			States	(	1
				State	(
					Duration ( 0.0 )
					LightColour ( 80ff0000 )
					Position ( -1.052 1.42 12.72 )
					Azimuth ( 0 0 0 )
					Transition ( 0 )
					Radius ( 0.9 )
				)
			)
		)	
	)
	